[project]
name = "ai-invoice-auditor"
version = "0.1.0"
description = "AI Agentic Invoice Auditor with A2A & MCP integration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langgraph",
    "langchain-aws",
    "langchain-core",
    "pydantic>=2.0",
    "fastapi",
    "uvicorn",
    "loguru",
    "fpdf",
    "qdrant-client",
    "litellm",
    "ragas",
    "datasets",
    "pandas",
    "fastmcp",
    "a2a-python",
    "mcp",
    "presidio-analyzer",
    "presidio-anonymizer",
    "pdfplumber",
    "pytesseract",
    "pillow",
    "python-multipart",
    "nest_asyncio",
    "instructor",
    "python-dotenv",
    "rich"
]

[tool.uv]
dev-dependencies = [
    "pytest",
    "ruff",
    "mypy"
]